npm test -- tests/unit
npm test -- tests/integrated/student.test.js 
npm test -- tests/integrated/university.test.js
npm test -- tests/integrated/annotations.test.js
npm test -- tests/integrated/package.test.js
npm test -- tests/integrated/Program.test.js
npm test -- tests/integrated/resources.test.js
npm test -- tests/integrated/Subject.test.js
npm test -- tests/integrated/Syllabus.test.js
npm test -- tests/integrated/paper.test.js